# Generated by Django 5.1.6 on 2025-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_courses_customuser_balance_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(max_length=255, upload_to='course_images/'),
        ),
    ]
