# Generated by Django 5.1.6 on 2025-02-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(max_length=255, upload_to='images/'),
        ),
    ]
