# Generated by Django 5.1.6 on 2025-02-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.ImageField(max_length=255, upload_to='images/')),
            ],
        ),
    ]
